---
title: "1.2 — Externalities and Bargaining — Class Content"
draft: false
linktitle: "1.2 — Externalities and Bargaining"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.2-slides"
---

{{% alert note %}}
*Monday, January 31, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview


## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading
- [<i class="fas fa-file-pdf"></i> Coase, 1960, "The Problem of Social Cost"](/readings/Coase-1960.pdf)

## Optional but Useful Reading

- [<i class="fas fa-file-pdf"></i> Coase, 1992, "The Institutional Structure of Production"](/readings/Coase-1992.pdf)
- [<i class="fas fa-file-pdf"></i> McCloskey, 1998, "The So-Called Coase Theorem"](/readings/Mccloskey-1998.pdf)
- [<i class="fas fa-file-pdf"></i> Medema, 2020, "The Coase Theorem At Sixty"](/readings/Medema-2020.pdf)
- [<i class="fab fa-wikipedia-w"></i> Pierson v. Post](https://en.wikipedia.org/wiki/Pierson_v._Post)
- [<i class="fas fa-external-link-square-alt"></i> Pierson v. Post (Opinion of the  Court)](http://www.courts.state.ny.us/reporter/archives/pierson_post.htm)

It is important that you understand what it is Coase is trying to say, and hence, I have provided several additional readings that are optional, but highly recommended to assist in your interpretation. Coase (1992) is his Nobel Prize lecture, and in part, he reflects on the meaning of Coase (1960). McCloskey (1998) provides a good interpretation of what Coase’s actual point was, which got lost in George Stigler’s formulation of the “Coase Theorem.” Medema (2020) provides a highly extensive discussion of all of the debates, interpretations, and applications of the Coase theorem over ythe past 60 years.


We look at [https://scholar.google.com/scholar?cluster=10739117159072125396&hl=en&as_sdt=0,9](one of the most cited-papers in the 20th century), which almost single-handedly launched the discipline of [Law and Economics](https://laws21.classes.ryansafner.com), one of the two papers that won Coase the 1991 Economics Nobel Prize. It is also quite lengthy and detailed, weaving back and forth between theoretical examples and real world legal cases. You will have a full week to read this, but **focus on sections I, II, V, VI, VII, the last paragraph on p.27-p.29, IX, X**.

- Coase uses many examples, often involving complex legal cases. The laws and quotes of the opinions of judges is not important here. You need not remember or master them all, but understand the consistent logic behind all of them.
- This article is credited with the creation of "The Coase Theorem." What is it, according to Coase?
- What kind of studies or examinations is Coase calling for economists to do that they did not normally do before?
- How do transaction costs (Coase calls these "the cost of using the market") change or affect his model/examples?
- What is the Pigouvian approach to externalities, and what does Coase have to say about it?
- What is the decision that needs to be made, according to Coase, when attempting to resolve an externality?  

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`