---
title: "1.5 — Public Goods, Club Goods, and the Commons — Class Content"
draft: false
linktitle: "1.5 — Public Goods, Club Goods, and the Commons"
date: "2020-06-08"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "1.5-slides"
---

{{% alert note %}}
*Wednesday, February 9, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we are going to consider different types of goods — public goods, club goods (or “toll” goods), and the commons (or “common pool resource”) — and the organizational challenges needed to successfully provide them. Each of these topics, and the research program behind each of them, deserves their own day, but we need to press ahead and it makes sense to lump these together.

A fundamental problem that will be relevant this entire semester, is the logic of collective action, first extensively explored by Mancur Olson in a 1965 book with that title (*The Logic of Collective Action*). I have given you a short chapter from a later book of his, *The Rise and Decline of Nations* that discusses some of the key ideas.

On the commons, it is difficult to find a good short introduction to the extensive research program by Elinor Ostrom (first woman to win an Economics Nobel prize) and her colleagues, so I recommend you watch or read her Nobel Prize address.

## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading
- *Skim* [<i class="fas fa-file-pdf"></i> Olson (1982), *The Rise and Decline of Nations*, Chapter 2, "The Logic"](/readings/Olson-1982.pdf)
- *Skim Read or Watch* [<i class="fas fa-file-pdf"></i> Elinor Ostrom 2009 Nobel Prize Lecture: “Beyond Markets and States: Polycentric Governance of Complex Economic Systems”](https://www.nobelprize.org/prizes/economic-sciences/2009/ostrom/biographical/)

## Optional/Referenced Reading

### Public Goods and Collective Action

- [<i class="fas fa-file-pdf"></i> Samuelson, 1954, "The Pure Theory ofo Public Expenditures"](/readings/Samuelson-1954.pdf)
- [<i class="fas fa-file-pdf"></i> Safner, 2020, "'Public Good,' or 'Good for the Public?' Political Entrepreneurship and the Public Funding of Scientific Research"](https://ryansafner.com/publication/public-good-or-good-for-the-public/)
- [<i class="fas fa-file-pdf"></i> Iannaconne, 1992, "Sacrifice and Stigma: Reducing Free-riding in Cults, Communes, and Other Collectives"](/readings/Iannaconne-1992.pdf)
- [<i class="fas fa-podcast"></i> *Econtalk*: Iannaconne on the Economics of Religion](https://www.econtalk.org/the-economics-of-religion/)

### Club Goods
- [<i class="fas fa-file-pdf"></i> Buchanan, 1965, "An Economic Theory of Clubs"](/readings/Buchanan-1965.pdf)

### Commons

- [<i class="fab fa-youtube"></i> MR University: "Women in Economics: Elinor Ostrom"](https://learn.mru.org/women-economics-series-elinor-ostrom/) (solving tragedy of the commons)
- [<i class="fas fa-file-pdf"></i> Safner, 2016, "Institutional Entrepreneurship, Wikipedia, and the Opportunity of the Commons"](https://ryansafner.com/publication/institutional-entrepreneurship-wikipedia-and-the-opportunity-of-the-commons/)

## Questions to Guide Your Reading

- What are the similarities/differences between individual interests and group interests (for groups to which individuals belong)?

- What does Olson say is Marx's shortcoming of his approach to groups (economic classes)?

- What are the economic differences between large groups and small groups, in terms of individual incentives?

- Why might groups fail to achieve their stated goals?

- What are "selective incentives," why are they important, and what may be some examples?  

- Connect Olson’s idea of selective incentives with Ostrom’s approach to understanding rules that best govern common pool resources. 

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`