---
title: "2.2 — Liberalism and the State — Class Content"
draft: false
linktitle: "2.2 — Liberalism and the State"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.2-slides"
---

{{% alert note %}}
*Wednesday, February 23, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Last class was about **government placing constraints on citizens**, and it being in everyone's interest to accept these. This class is about **citizens placing constraints on government.** We might summarize this dual dilemma by paraphrasing Madison's Federalist 51:

> "In framing a government which is to be administered by men over men, the great difficulty lies in this: you must first enable the government to control the governed; and in the next place oblige it to control itself."

This class contains three readings, in order to connect with the previous class. The famous counterweight or improvement to Hobbes' 1651 *Leviathan* is John Locke's 1689 *Second Treatise on Government*. Both Locke and Hobbes consider the State as a social contract rational individuals construct to escape the state of nature. In contrast to Hobbes, Locke sees humanity as far more sociable in the state of nature, able to make cooperative agreements, discover, and apply "the laws of nature." Yet, creating a civil government improves on what he sees as the three "inconveniences" of anarchy. We have already seen Locke's view of the origin of legitimate property rights, but I included the relevant passage again for reference. Most importantly, Locke famously arguers that the ultimate aim of the State is to protect individual property rights.

Second, we extend classic political philosophy to the crafting of the United States Constitution in the late 1780s. James Madison - the intellectual "father of the Constitution" - along with Alexander Hamilton and John Jay psudonymously wrote what later became known as *"The Federalist Papers,"*, then a series of newspaper articles arguing in favor of ratifying the proposed Constitution that emerged out of the Philadelphia convention in 1787. These writings are among the most important pieces of Western (and especially, *American*) political philosophy still relevant today. We read the two most cited papers, Federalist 10 and 51 (both allegedly written by Madison) focusing on the danger of factions, and the tyranny of majorities (or minorities). We see that the American Founders, exemplified by Madison, were deeply suspicious of pure democracy and its vices of tyranny, demagoguery, and economic populism (namely, the redistribution of property and cancellation of debts).

I would focus more on Federalist 10 and its important discussion of factions, and Madison's novel argument of how to contain factions, though I included Federalist 51 because it is both short, and full of the era's most memorable phrases. 

Finally, we consider Benjamin Constant’s famous essay comparing how the Ancients view “liberty” as the public privileges and duties of a citizen versus how we “Moderns” view liberty as the right to live our private lives with limited interference. While certainly not the first to advocate the core ideas (Locke, for example is most of the way there) of rule of law, pluralism & toleration of others, and an appreciation of commerce, Constant was the perhaps the first thinker to consciously refer to himself as a “liberal.” This conception of the relationship between the individual and the State —  *liberal democracy* that empowers majorities but protects individual rights — is the bedrock of modern political philosophy in the West. Modern political ideologies (though there are rising *illiberal* tendencies of late) — progressivism, conservatism, and libertarianism — share their origins in liberalism.

## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading
- [<i class="fas fa-file-pdf"></i> Locke (1689), Selections from *The Second Treatise on Government*](/readings/Locke-1689.pdf)
- [<i class="fas fa-file-pdf"></i> Madison (1787-1788), *Federalist* 10 and 51](/readings/Madison-1787.pdf)
- [<i class="fas fa-file-pdf"></i> Constant, (1819), “The Liberty of the Ancients as Compared with that of the Moderns”](/readings/Constant-1819.pdf)

# Recommended Readings

- [<i class="fas fa-external-link-square-alt"></i> July 4, 1776 - U.S. *Declaration of Independence*](https://www.archives.gov/founding-docs/declaration-transcript)

Look at the first two paragraphs of the U.S. Declaration of Independence, which is the foundational document in the political philosophy of America. Observe the connections to Locke in terms of the origin and purpose of government.   

## Questions to Guide Your Reading

- What is the role of faction (interest groups) in power?

- How does Madison suggest we deal with the problem of factions?

- What's wrong with "finding the right people" to rule us?

- What tyranny(ies) should we watch out for? The majority? The minority? The rulers? The ruled?

- What constrains those in the nexus of power to be on their best behavior (or fails to constrain them)?

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`