---
title: "2.3 — Constitution Something — Class Content"
draft: false
linktitle: "2.3 — Liberalism and the State"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "2.2-slides"
---

{{% alert note %}}
*Wednesday, March 2, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

We are rapping up our discussion of constitutional political economy before diving into politics under the constitution we *have* (i.e. assuming our constitutional rules are fixed) in Unit I. I want to discuss two major concepts and problems, which again will venture into political philosophy and normative territory.

First, a reminder about shifting focus between *pre-*constitutional rules and *post*-constitutional rules. This is one of the things Buchanan is getting at with his somewhat vague and frustrating idea of the “relatively absolute absolutes.” As part of this, Buchanan gives the *status quo* a special status, that it needs no justification, but that changes from it do require justification. The rules, traditions, and customs that we currently follow should be treated as absolute and given, but only *relatively* — in that we can ultimately and eventually change them as needed, but not too hastily. 

This gets us into the second idea that I want to discuss: the role of tradition and in changing constitutional rules. This comes across in Buchanan, but I also gave you a chapter by Hayek where he gives his characteristic account of how rules and rule-following behavior emerge over time in human society. It is more about gradual and unconscious cultural evolution that often *restrains* our moral intuitions as opposed to what he calls “rational constructivism” (humans rationally designing the system of rules and customs). This brings up a conflict between our moral intuitions (that come from the fact that we historically evolved in tribal settings) and the market-based society that Hayek calls “the extended order”. Similar to Buchanan, it also places some level of importance on ingrained tradition. Hayek, while [not a political conservative](https://www.cato.org/sites/cato.org/files/articles/hayek-why-i-am-not-conservative.pdf)^[Note, Buchanan also wrote [a book with a similar title](https://www.amazon.com/Why-Too-Not-Conservative-Liberalism/dp/1845423143)], holds tradition and customs with *some* reverence due to this.

Both Buchanan and Hayek do, however, recognize the need to subject specific norms, traditions, and customs to criticism and change or removal. This is essential to progress, and there are many illiberal customs that are worthy of us abandoning. However, both caution that we should not be too hasty to throw out something we do not fully understand the consequences of, and we should be skeptical of calls for sudden, major social changes, especially of the rational constructivist variety.

Related to this, many recognize flaws in our current constitution, and some go so far as to say we should change the constitution or perhaps even call a new constitutional convention. Right now the country of Chile is in the process of creating a new constitution, something worth examining.

## <i class="fas fa-book-reader fa-lg"></i> Readings

## Required Reading
- [<i class="fas fa-file-pdf"></i> Hayek (1989), “Between Instinct and Reason”, Ch.1 in *The Fatal Conceit*](/readings/Hayek-1989-Ch1.pdf)
- [<i class="fas fa-file-pdf"></i> Buchanan, 1999, “The Relatively Absolute Absolutes”](/readings/Buchanan-1999b.pdf)

# Recommended/Referenced Readings

- [NY Times (Dec. 28, 2021), “Chile Writes a New Constitution, Confronting Climate Change Head On”](https://www.nytimes.com/2021/12/28/climate/chile-constitution-climate-change.html)
- [NBC News (July 8, 2021), “Making history: Chileans start work on first constitution equally drafted by women, men”](https://www.nbcnews.com/news/latino/making-history-chileans-start-work-first-constitution-equally-drafted-rcna1353)
- [Foreign Policy, (May 21, 2021), “Chile’s Constitution Is Too New for Its Own Good”](https://foreignpolicy.com/2021/05/21/chiles-constitution-is-too-new-for-its-own-good/)
- [*Econtalk* (Dec 20, 2021): Munger on Constitutions](https://www.econtalk.org/michael-munger-on-constitutions/)
## Questions to Guide Your Reading

- What are Buchanan’s idea of the “relatively absolute absolutes?”

- How are the relatively absolute absolutes related to shifting our focus between constitutional rules and political rules?

- How is Hayek’s comparison of writers 

- How does Hayek’s account of where our rules come from conflict with the “social contractarian” view of the State (think about Hobbes and Locke)?

- What is “between instinct and reason?”

- What does Hayek call “the fatal conceit?”

- What does Hayek call “constructivist rationalism?” What is Hayek’s position?

- How should we approach “tradition?”

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`