---
title: "3.2 — Voting II: Ignorance & Irrationality — Class Content"
draft: false
linktitle: "3.2 — Voting II: Ignorance & Irrationality"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.2-slides"
---

{{% alert note %}}
*Monday March 21, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we will discuss the (in)famous concept of **rational ignorance**, as well as **rational irrationality**. Your reading for today is on the latter, since it is more debatable, and since I can explain the former to you very quickly in class (and give a demonstration). 

This is a good summary of the argument made by Caplan's similarly-titled full-length book: *The Myth of the Rational Voter, Why Democracies Choose Bad Policies*. Feel free to skim the last few sections, once you get the idea about what the biases Caplan argues are.

## <i class="fas fa-book-reader fa-lg"></i> Readings

### Required Reading

- [<i class="fas fa-file-pdf"></i> Caplan (2007), "The Myth of the Rational Voter"](/readings/Caplan-2007.pdf)

### Recommended Reading

- <i class="fas fas fa-book"></i> Holcombe (2016), *Advanced Introduction to Public Choice*, Chs. 6
- [<i class="fas fa-file-pdf"></i> Somin (2004), "When Ignorance Isn’t Bliss"](/readings/Somin-2004.pdf)

Your Holcombe "textbook" does discuss both rational ignorance, voter turnout, and rational irrationality in this brief chapter.

Somin’s piece goes into more detail specifically about the concept of rational ignorance (and he has several recent books on the topic).

### Questions to Guide Your Reading

- According to Caplan, what are the four systematic biases?

- What is "rational ignorance"?

- What is Caplan's idea of "rational irrationality" and how is it different from "rational ignorance?"

- How does the Median Voter Theorem fit into Caplan's framework? 

- What is "the miracle of aggregation," how does it work, and why does Caplan argue it is not relevant for voting?

- Why do people vote or not vote? How do people that do vote choose how they vote?

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`