---
title: "3.3 — Interest Groups — Class Content"
draft: false
linktitle: "3.3 — Interest Groups"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.3-slides"
---

{{% alert note %}}
*Wednesday March 23, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Today we briefly discuss the logic of interest groups, and moreso about the effects they have on public policy and regulation. Your readings focus on both the economic outcomes of regulation and a theory of how and why regulation favors particular groups.

Stigler's paper is one of the [most cited works](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C21&q=the+theory+of+economic+regulation&btnG=) in the economics of regulation, but of course it is 50 years old. His numbers are out of date, and his regressions are extremely simple (remember, this is before computers did this!), so you don't need to pay close attention to the numerical examples of his. You *should* however, pay attention to the general trends, and his theoretical explanation of *why* these trends in regulation occur. 

Yandle's paper is short and easy to read, but is one of the more useful “behind-the-scenes” explanations of regulation and public policy out there (from a former insider). 

I will also cover some background on how Olson’s logic of collective action affects public policy. For more on this, and a list of examples, see the recommended papers below. Mitchell’s paper collects lots of examples and key strategies that interest groups or firms employ to obtain political privileges at others’ expense. I also added a working paper my colleague Vlad Tarko and I submitted to the journal *Public Choice* (revise and resubmit requested) about extending Stigler’s 1971 model to account for the diversity of regulatory regimes around the world (feedback is always welcome!).

## <i class="fas fa-book-reader fa-lg"></i> Readings

### Required Reading

- [<i class="fas fa-file-pdf"></i> Stigler, George J, 1971, “The Theory of Economic Regulation,” *The Bell Journal of Economics and Management Science* 2(1): 3-21](/readings/Stigler-1971.pdf)
- [<i class="fas fa-file-pdf"></i> Yandle, Bruce, 1983, “Bootleggers and Baptists: The Education of a Regulatory Economist,” *Regulation* 7(3): 12-16](/readings/Yandle-1983.pdf)

### Recommended Reading

- [<i class="fas fa-file-pdf"></i> Mitchell, Matthew (2013), “The Pathology of Privilege”](/readings/Mitchell-2013.pdf)
- [<i class="fas fa-file-pdf"></i> Tarko, Vlad and Ryan Safner, 2022, “The Variety of Regulatory Regimes”](/readings/Tarko-Safner-2022.pdf)

### Questions to Guide Your Reading

- How is much of the theory of regulation, of the importance of interest groups, and the types of policies that get enacted predicted by Mancur Olson's *Logic of Collective Action*?

- According to Stigler, why does economic regulation look the way it does? Who is it designed for? What types of regulation are we more (or less) likely to see?

- According to Yandle, multiple interests favor similar regulation for different reasons. Which kinds of arguments are those calling for certain regulations more likely to use in public than in private?

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`