---
title: "3.5 — Bureaucracy — Class Content"
draft: false
linktitle: "3.5 — Bureaucracy"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.5-slides"
---

{{% alert note %}}
*Monday April 4, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

We now look at those individuals and organizations that actually *implement* the laws, collectively known as "the bureaucracy," sometimes called "the fourth branch of government." These are both executive-branch departments (e.g. Department of Commerce, Department of Education, Department of Transportation, etc.) and independent agencies created by Congress (e.g. Federal Communications Commission, Federal Trade Commission, Securities and Exchange Commission, etc.) that are staffed with individuals that collectively create rules about what private individuals and entities may or may not do, or must do, as directed by Congress or the President, colloquially known as "regulation."

What do these organizations (we might call them "bureaus", "agencies," "departments", etc) and the individuals that comprise them ("bureaucrats," "government agents," etc) do? How do they interact with other players in collective choice (voters, politicians, interest groups, legislatures, courts, etc)?

Your textbook (Holcombe) chapter gives a good overview of this area of research, and the **optional** section from Mises' textbook gives a good overview of understanding the differences and similarities between organizations that produce for-profit in the market, and organizations (like bureaus) that produce politically.

## <i class="fas fa-book-reader fa-lg"></i> Readings

### Required Reading

- <i class="fas fas fa-book"></i> Holcombe (2016), *Advanced Introduction to Public Choice*, Ch. 9 "Bureaucracy"
- <i class="fas fas fa-book"></i> Mises, Ludwig von (1949), *Human Action: A Treatise on Economics*, [Ch. XV.10, "Promoters, Managers, Technicians, and Bureaucrats"](/readings/Mises_1949_Bureaucrats.pdf) (Skim)

### Recommended Reading

### Questions to Guide Your Reading

- How much should we consider bureaus as *suppliers* vs. *demanders* of public regulation?

- What are the key differences between a profit-maximizing firm in the private sector and a government agency/bureau? What does a bureau maximize? What are its constraints? What about an *individual* bureaucrat working at an agency?

- Who are the "customers" of a bureau? How does it interact or bargain with them? Who has more information?

- How do bureaus interact or compete with one another for funding from Congress?

- What is the relationship between the bureau, Congress, the sponsoring committee that oversees the bureau, and the courts?

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`