---
title: "3.7 — Federalism — Class Content"
draft: false
linktitle: "3.7 — Federalism"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "3.7-slides"
---

{{% alert note %}}
*Monday, April 11, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

We will wrap up our "structural" look at the major political groups and institutions in American-style democracy with a look at *federalism* - the multiplicity of governments (federal, state, and local) each with authority over different domains of American life.

Weingast (1995) is a pretty famous paper in political economy; he uses a fairly straightforward application of the game theory of credible commitment problems to explain how a federalist system such as the United States can successfully constrain government from abusing its power. We did not cover much game theory in this course, so don't get too hung up on his model(s), the paper is otherwise pretty clear verbally, and he has some good historical examples to apply his framework.

## <i class="fas fa-book-reader fa-lg"></i> Readings

### Required Reading

- [<i class="fas fa-file-pdf"></i> Weingast (1995), “The Economic Role of Political Institutions: Market-Preserving Federalism and Economic Development”](/readings/Weingast-1995.pdf)

### Recommended Reading

- [<i class="fas fas fa-book"></i> Holcombe (2016), *Advanced Introduction to Public Choice*, pp. 102-104 on Federalism
- [<i class="fab fa-wikipedia-w"></i> Wikpedia: Tiebout Competition](https://en.wikipedia.org/wiki/Tiebout_model)

### Questions to Guide Your Reading

- What is "federalism" in the United States?

- What is the role of the constitution in coordinating social groups and in restraining abuse? (frame it as a credible commitment problem!) 

- How do political institutions affect economic prosperity?

- What specifically about England/the United States' political institutions allowed for economic prosperity? How does this apply to China?

- What is the difference between federalism (plain) and market-preserving federalism? 

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`