---
title: "4.3 — Corruption and Reform — Class Content"
draft: false
linktitle: "4.3 — Corruption and Reform"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.3-slides"
---

{{% alert note %}}
*Wednesday, April 20, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

Jonathan Rauch has an interesting argument about why U.S. politics today is so divisive and ineffective: activists have reformed "corruption" out of the system too much that politicians can no longer make the necessary (and ugly) deals that good governance may require. It's much more politically palatable to rail against corruption and propose reforms than to actually get one's hands dirty and govern properly (via pork, logrolling, secret deals and agreements, etc).

Perhaps this might connect with the rise of the administrative state?

Rauch has been making this argument, or variations on this theme, for years. I had originally thought about having you read more recent articles by him on this subject, which incorporate recent current events with the 2016 election, or the current electoral cycle for 2020. I ultimately decided to stick with an earlier, 2014, article, so you can see how this idea is not something that started with Trumpism or 2016, it has long been a problem slowly bubbling to the surface in our politics. I've included two more recent articles that apply this argument to recent events if you are interested.

## <i class="fas fa-book-reader fa-lg"></i> Readings

Note we will be holding our discussions on the Blackboard discussion board for this topic. You do not need to email questions in advance. 

### Primary Reading

- [<i class="fas fa-file-pdf"></i> Rauch, (2014), "Political Realism: How Hacks, Machines, Big Money, and Backroom Deals Can Strengthen American Democracy," *Brookings*](/readings/Rauch-2014.pdf)

### Recommended Readings

- [<i class="fas fa-file-pdf"></i> Rauch, (2016), "How American Politics Went Insane," *The Atlantic*](https://www.theatlantic.com/magazine/archive/2016/07/how-american-politics-went-insane/485570/)
- [<i class="fas fa-file-pdf"></i> Rauch and La Raja, (2019), "Too Much Democracy Is Bad for Democracy," *The Atlantic*](https://www.theatlantic.com/magazine/archive/2019/12/too-much-democracy-is-bad-for-democracy/600766/)

### Questions to Guide Your Reading

- What is "transactional politics" or "political realism" and what is its role in good governance?

- Why has "transaction politics" declined over the 20th century?

- What did James Q. Wilson have to say about the difference between "amateurs/activists" and "professionals" in politics?

- What is/was the role of "backroom deals," "political machines," and "gatekeepers" in politics (particularly in political parties and their primaries)?

- (How) does this evolution explain the rise of "outsider" candidates like Donald Trump and Bernie Sanders?

- Does this explain the apparent abdication of Congress and legislatures to properly legislate, and abdicate much of the *actual governing* to the unaccountable agencies in the administrative state?

## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`