---
title: "4.7 — The Dark Web — Class Content"
draft: false
linktitle: "4.7 — The Dark Web"
date: "2020-02-17"
menu:
  content:
    parent: Course content
    weight: 2
type: docs
output:
  blogdown::html_page:
    toc: true
slides: "4.7-slides"
---

{{% alert note %}}
*Wednesday, May 3, 2022*
{{% /alert %}}

## <i class="fas fa-info-circle fa-lg"></i> Overview

TBD 

## <i class="fas fa-book-reader fa-lg"></i> Readings

### Required Reading

- [<i class="fas fa-file-pdf"></i> Hardy and Norgaard, 2016, “Reputation in the Internet black market: an empirical and theoretical analysis of the Deep Web”](/readings/Hardy-Norgaard-2016.pdf)

### Recommended Readings

- [<i class="fas fa-file-pdf"></i> Norgaard, Walbert, and Hardy, 2018, “Shadow markets and hierarchies: comparing and modeling networks in the Dark Net”](/readings/Norgaard-Welbert-Hardy-2018.pdf)
- [<i class="fas fa-podcast"></i> *NPR Planet Money* 585: “Chasing the Dread Pirate Roberts”](https://www.npr.org/sections/money/2014/11/26/365510643/episode-585-chasing-the-dread-pirate-roberts)

### Questions to Guide Your Reading

TBD 
## <i class="fas fa-chalkboard-teacher"></i> Slides

Below, you can find the slides in two formats. Clicking the image will bring you to the html version of the slides in a new tab. Note while in going through the slides, you can type <kbd>h</kbd> to see a special list of viewing options, and type <kbd>o</kbd> for an outline view of all the slides.

The lower button will allow you to download a PDF version of the slides. I suggest printing the slides beforehand and using them to take additional notes in class (*not everything* is in the slides)!

`r blogdown::shortcode("slide-links")`