---
title: Assignment Details
menu:
  assignments:
    parent: Assignments
    weight: 1
type: docs
weight: 1
toc: false
---

On this page, you can find more information about each individual assignment, as well as the assignments themselves.

- [<i class="fas fa-calculator"></i> `Grade Calculator`](https://ryansafner.shinyapps.io/dev_grade_calculator/) 

Use this tool to help calculate your overall course grade using existing assignment grades, as well as forecast "what if" scenarios.

Please refer to the [syllabus](/syllabus) for more information about grades.

# Country Profile {-}

Each of you will write a short profile of a different developing country and give a short presentation to the class. The countries that may be chosen will be restricted to developing economies in Latin America, Asia, Africa, and Eastern Europe. Students born outside of the U.S. may *not* choose the country of their birth. The purpose of this assignment is to "get you out of your comfort zone" and see the world from the perspective of a culture and an economy radically different than the one(s) you are familiar with.

# Participation and Discussion {-}

At the end of most major topics, we will hold a graded, in-class discussion focused on the readings and lectures.

# Short Papers {-}

There will be two short papers on assigned topics. The first will be early in the semester, covering topics from the first several weeks. The second will cover topics from the remaining weeks. I am looking for 3-5 page papers that explore subjects prompted by questions that I will provide to you in advance. However, I also encourage you to take the less-trodden path and explore something unique and interesting to you.

# Final exam {-}

The take-home final exam will be a series of essay questions.