---
title: "Final Exam"
draft: false
#linktitle: "Discussions"
date: "2020-06-08"
menu:
  assignments:
    parent: Assignments
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: true
---

{{% alert warning %}}
Due by the end of the day Friday May 13 by email.
{{% /alert %}}

# Instructions

Choose four questions to answer. Questions draw from course lectures, discussions, and readings. Your answers, given the time and resources at your disposal, should be complete yet concise (e.g. 2-3 well-reasoned paragraphs).

You may discuss the questions, but you must write your own responses and turn in your own work. Answers that are substantially similar will be interpretted cheating and punished accordingly. I will not answer any questions about course content during while the exam is outstanding.

You will be graded both on your use of reasoning and economic analysis, and ability when relevant to accurately describe the arguments in the readings. Where asked for your opinion, you will not be graded on your *conclusion*, only your *reasoning.* You must be able to talk with some familiarity about arguments put forth in our readings, when relevant (informally, as in “According to Buchanan...”). You do not need formal citations, but it should be clear when you are referencing the readings vs. your own thinking.

Each question is worth **25 points**

1. Explain in your own words the concept of Tiebout competition — how it works, and what its main features/benefits are. How does the federalism of government in the U.S. promote Tiebout competition?

2. Explain the arguments for and against a Common Ownership Self-Assessed Tax as proposed by Posner & Weyl. Do you find any convincing?

3. Is our political system in the United States broken because we do not have enough “corruption?” Summarize the argument that politics needs to be more transactional, as made by Jonathan Rauch. Do you agree or disagree?

4. According to Albert Hirschman, is it better to have a monopolist with “slack” (e.g. laziness or incompetence) where all citizens are “locked-in” with no alternatives to the monopoly, or a slacking monopolist where consumers do have alternatives? Explain. Do you agree or disagree?

5. In what specific ways are government agencies (bureaus) & the employees/managers that comprise them different from profit-seeking firms & the employees/managers that comprise them in the marketplace?

6. What are the flaws with one person, one vote? Explain the arguments in favor of and against Posner & Weyl’s proposal of “quadratic voting.” Do you think this might be an improvement over our current system of “one person one vote?” 

7. Which topic/concept/proposal this semester was your favorite, or you found most surprising or interesting, and why?