---
title: "Midterm Exam"
draft: false
#linktitle: "Discussions"
date: "2020-06-08"
menu:
  assignments:
    parent: Assignments
    weight: 1
type: docs
output:
  blogdown::html_page:
    toc: true
---

{{% alert warning %}}
Due by 8:00 PM Friday April 1 by email.
{{% /alert %}}

# Instructions

Choose four questions to answer. Questions draw from course lectures, discussions, and readings. Your answers, given the time and resources at your disposal, should be complete yet concise (e.g. 2-3 well-reasoned paragraphs).

You may discuss the questions, but you must write your own responses and turn in your own work. Answers that are substantially similar will be interpretted cheating and punished accordingly. I will not answer any questions about course content during while the exam is outstanding.

You will be graded both on your use of reasoning and economic analysis, and ability when relevant to accurately describe the arguments in the readings. Where asked for your opinion, you will not be graded on your *conclusion*, only your *reasoning.* You must be able to talk with some familiarity about arguments put forth in our readings, when relevant (informally, as in “According to Buchanan...”). You do not need formal citations, but it should be clear when you are referencing the readings vs. your own thinking.

Each question is worth **25 points**

1. Why is the United States not a pure democracy? Answer using relevant insights from the readings and from class.

2. What is the function of constitutional rules? Use relevant insights from the readings.

3. How does vote cycling (Condorcet’s paradox) undermine democracy? Under what conditions does it occur? Under what conditions can we avoid it? How do real world political institutions avoid cycling?

4. Explain Buchanan and Tullock’s optimal decision rule model. Give examples of (i) situations where decision rules closer to requiring unanimity are optimal, (ii) situations where decision rules further from unanimity are optimal, and (iii) when it is optimal to not act collectively.

5. Why can democracies tend to produce “bad” or inefficient public policies? Explain at least three different theories/explanations and describe an example of each.

6. It is an extremely common argument that in order to fix the flaws in public policy or our politics, we just need to “elect the right people.” Use what you have learned in this class to react to this argument.

7. In what ways are business firms, clubs, and States similar solutions to scenarios that require a group choice? In what ways are they different?